### ISSUE TITLE
Misc data quality tracker

### ISSUE THREAD

**Issue by droher** [droher/baseball.computer.rs#38]
- [ ] Many old box score files missing park id
- [x] Some Negro League games have null ump entries when they should just be not included e.g. https://github.com/droher/retrosheet/blob/master/nlb/allstar/1933EW.EB#L20
- [ ] Incorrect/dupe box phlines, blines
- [ ] Files/games duplicated across directories - rosters, Negro League games
